language: node_js
node_js:
    - "6.7"
script:
    - echo "Deploying!"
install:
    - npm install -g firebase-tools
    - npm install -g angular-cli
    - npm install
    - ng build --prod
after_success:
    - firebase deploy --token "$FIREBASE_TOKEN" --project fire2bowyer